services:
  next-app:
    image: node:latest
    ports:
      - 0:3000
    working_dir: /app
    volumes:
      - ./next-app:/app/
      - /app/node_modules
    command: sh -c "npm install && npm run dev" # 自动安装依赖并启动
    networks:
      - software-network
networks:
  software-network:
    external: true
