include:
  - ./../MongoDB/docker-compose.yml
networks:
  software-network:
    external: true
services:
  crawlab:
    image: crawlabteam/crawlab
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongodb-mongo-1"
    ports:
      - "0:8080"
    restart: unless-stopped
    networks:
      - software-network
