services:
  latest:
    image: composer:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - ./:/app
    # command: composer init --name docker/composer-create --author docker --stability alpha --license MIT
    command: composer init
    restart: unless-stopped
    networks:
      - software-network
    # working_dir: /usr/src/app
    # volumes:
    #   - ./composer-created:/usr/src/app
    # command: composer init --name docker/composer-create --author docker --stability alpha --license MIT
    # command: composer create-project --prefer-dist laravel/laravel ./laravel5 5.5.
networks:
  software-network:
    external: true
