services:
  amh:
    image: alibabacloud/amh:latest
    # container_name: software
    ports:
      - 0:8080
    environment:
      - TZ=Asia/Shanghai
    # volumes:
    #   - ./_/:/
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
