networks:
  software-network:
    external: true
services:
  latest:
    image: mysql
    ports:
      - "0:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - "./data:/var/lib/mysql"
      - "./config:/etc/mysql/conf.d"
    restart: unless-stopped
    networks:
      - software-network
