services:
  alpine:
    image: node:alpine
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - ./~:/app
    networks:
      - software-network
  latest:
    image: node:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - ./~:/app
    # command: npx hexo init new-hexo-app # 自动安装依赖并启动
    networks:
      - software-network
  v20:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "0:3000"
    volumes:
      # - ./node-20:/usr/src/app
      - /use/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm init -y && node index.js" # 自动安装依赖并启动
    networks:
      - software-network
networks:
  software-network:
    external: true
