networks:
  software-network:
    external: true
services:
  8.2-fpm:
    image: php:8.2-fpm
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - 8.2-fpm:/app
    restart: unless-stopped
    networks:
      - software-network
  7.4.33-fpm:
    image: php:7.4.33-fpm
    stdin_open: true # docker run -i
    tty: true # docker run -t
    working_dir: /app
    volumes:
      - 7.4.33-fpm:/app
    restart: unless-stopped
    networks:
      - software-network
volumes:
  8.2-fpm:
  7.4.33-fpm:
