services:
  surveyking:
    image: surveyking/surveyking
    container_name: surveyking
    volumes:
      - ./_/app/files:/app/files # 文件目录，存储上传的文件，冒号左侧改成自己的，下同
      - ./_/app/logs:/app/logs # 运行日志
      - ./_/app/db:/app/db # 数据库文件
    ports:
      - 1991:1991 # 冒号左侧可改
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
