services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    ports:
      - 0:8080
    environment:
      - NODE_ENV=production
    # healthcheck:
    #   test: [ 'CMD', 'node', '/app/services/healthcheck' ]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
