services:
  cockpit:
    image: cockpit/websocket-bridge
    # container_name: software
    ports:
      - 0:9090
    environment:
      - TZ=Asia/Shanghai
    # volumes:
    #   - ./_/:/
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
