services:
  dpanel:
    image: dpanel/dpanel:latest
    container_name: dpanel # 更改此名称后，请同步修改下方 APP_NAME 环境变量
    ports:
      - 0:80
      - 0:443
      - 0:8080 # 替换 8807 可更改面板访问端口
    environment:
      APP_NAME: dpanel # 请保持此名称与 container_name 一致
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./_/dpanel:/dpanel # 将 /home/dpanel 更改为你想要挂载的宿主机目录
    restart: unless-stopped
    privileged: true
    networks:
      - software-network
networks:
  software-network:
    external: true
