services:
  wdcp:
    image: wdcp/wdcp
    # container_name: software
    ports:
      - 0:80
    environment:
      - TZ=Asia/Shanghai
    # volumes:
    #   - ./_/:/
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
