services:
  phpstudy:
    image: phpstudy/phpstudy:latest
    # container_name: software
    ports:
      - 0:80
      - 0:3306
    environment:
      - TZ=Asia/Shanghai
    # volumes:
    #   - ./_/:/
    restart: unless-stopped
    networks:
      - software-network
networks:
  software-network:
    external: true
