services:
  1panel:
    image: moelin/1panel:latest
    container_name: 1panel
    ports:
      - 0:10086
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    #   - ./_/var/lib/docker/volumes:/var/lib/docker/volumes
    #   - ./_/opt:/opt
    #   - ./_/root:/root
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    # network_mode: bridge
    networks:
      - software-network
networks:
  software-network:
    external: true
