# 基本信息
baseinfo:
  user_post: 前端开发
  user_name: 陈朗朗
  user_addr: 上海市宝山区
  user_mail: langnang.chen@outlook.com
  user_bday: 1995.07
# 教育背景
educations:
  - 2014.09~2018.06
    江苏科技大学
    信息管理与信息系统
    本科
# 职业技能
professional:
  - 熟练 HTML、DIV+CSS 的页面布局，能根据设计图完成页面制作；
  - 掌握 Sass 等 CSS 预处理器，使代码更具逻辑性，便于后期维护；
  - 掌握 ES6 常用语法，以及常用 JavaScript 库；
  - 熟悉 Vue + Element 框架，掌握 Vue 相关生态系统技术；
  - 掌握 Vue + Vant 框架，可实现移动端 h5 开发；
  - 掌握 PHP 、ASP.NET Core 和 SQL 语言并能够实现后端开发与数据库交互；
  - 了解 TypeScript ，在项目中可正常使用；
  - 熟悉使用 git 版本控制工具，进行代码管理。
# 工作经历
works:
  - company: 上海复深蓝软件股份有限公司
  - company: 研华科技(中国)有限公司
  - company: 金舟软件有限责任公司
# 项目经验
projects:
# 自我评价
evaluations:
# 自我评价
# 1、本人性格活泼开朗，能与他人良好的相处；2、对工作认真负责，具有很高的责任心和团队意识；
# 3、拥有独立开发能力，具有分析问题和解决问题的能力，能完美的完成项目需求；
# 4、善于钻研，对前端开发有浓厚的兴趣，重视用户体验，有着较为清晰的目标和计划，并且付诸实际行动；
# 5、工作之余我会时刻关注web前端开发的新技术，浏览一些前端网站，提高自己的技能水平，自己平时也喜欢写技术博客，并在csdn获得33万的阅读量，总排名1万+，把自己感兴趣和掌握的技术知识和大家一起分享 希望能帮助到有需要的人。
