networks:
  software-network:
    external: true
services:
  spider-flow:
    image: wbsu2003/spider-flow
    ports:
      - 0:8088
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_USERNAME=spider
      - SPRING_DATASOURCE_PASSWORD=YourStrongPassword
      - SPRING_DATASOURCE_URL=jdbc:mysql://spider-db/spiderflow?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&allowPublicKeyRetrieval=true
    restart: unless-stopped
    networks:
      - software-network

  spider-db:
    image: mysql:8.0
    container_name: spider-db
    volumes:
      - ./_/var/lib/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=RootPassword
      - MYSQL_DATABASE=spiderflow
      - MYSQL_USER=spider
      - MYSQL_PASSWORD=YourStrongPassword
      - MYSQL_INITDB_SKIP_TZINFO=true
    ports:
      - 3307:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - software-network
